[ADD] 카카오 회원가입, 로그인 구현
wecode-bootcamp-korea/41-2nd-BossBaby-backend pull request #5
Opened 2023-02-02 12:46 UTC by yeyunny

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항

**1. 각주는 수정 완료 후 삭제하겠습니다!**

**2. last_insert_id와 insertId의 차이점은 무엇일까요? 일단 insertId로 작성했으나 둘의 차이를 정확히 알고 싶습니다!**

**3. userService에서 새로운 유저임을 확인하는 checkKakaoUser와
기존 유저임을 확인하는 checkUserById 의 이름이 너무 비슷해서 구분이 어렵습니다..
어떤 네이밍이 좋을까요?**

2023-02-03 06:15 UTC, sangwoong03 reviewed
- checkUserByKakaoId 관련된 내용은 구두로 전달완료

- `last_insert_id`와 `inserId`는 그 역할이 동일합니다.
`INSERT ... ` 구문 이후에 row가 생성되고 auto_increment가 된 id 값을 반환합니다.

차이점은 다음과 같습니다.
`last_insert_id`는 sql 에서 사용할 수 있습니다.
즉 `Insert ...  ` 구문을 통해 어떤 데이터를 생성 한 이후 그 생성된 데이터가 가지는 id 값을 조회할 때 다음과 같이 사용할 수 있습니다.
```
SELECT LAST_INSERT_ID();
```

반면 insertId는 우리가 TypeOrm을 통해 raw 쿼리를 실행 후 반환되는 mysql의 raw result에서 사용할 수 있는 mysql 메서드입니다.
다음과 같이 사용할 수 있습니다. 

```javascript
const [ result ] = await database.query(... raw ...);
const insertId = result.insertId
```

2023-02-03 06:15 UTC, sangwoong03 commented on package.json
> +    "jest": "^29.4.1",
jest도 테스트를 위한 모듈이기 때문에 devDependencies에서 관리되면 좋을 것 같습니다.

2023-02-03 06:15 UTC, sangwoong03 commented on db/migrations/20230131120542_create_users_table.sql
> +phone_number VARCHAR(100) null,
현재 세번째 PR에 데이터베이스 관련된 migration 수정 PR이 보입니다.

해당 작업과 관련이 있는지 확인해주시고, 관련이 있다면 현재 PR에서 분리 후 migration fix하는 PR에서 관리될 수 있도록 수정해주세요.

2023-02-03 06:15 UTC, sangwoong03 commented on api/routes/userRouter.js
> +const userController = require("../controllers/userController");
모듈 구분을 통해 구조 파악이 용이하도록 라인브레이킹을 해주면 좋을 것 같습니다.
```suggestion
const express = require("express");
const router = express.Router();

const userController = require("../controllers/userController");
```

2023-02-03 06:15 UTC, sangwoong03 commented on api/services/userService.js
> +  console.log(result);
피드백 최종 반영 시 삭제!

2023-02-03 06:15 UTC, sangwoong03 commented on api/controllers/userController.js
> +  if (!kakaoToken) detectError("NEED_ACCESS_TOKEN", 401);
카카오 로그인을 위해 토큰을 받는 과정으로 보입니다.

다만 클라이언트가 전달하는 카카오 토큰이 없을 때 Access token이 없다는 에러 메시지를 반환할 경우, 인가 과정에서 accessToken을 전달하는 클라이언트에게 다소 애매한 에러메시지가 될 수 있을 것 같습니다.

```suggestion
  if (!kakaoToken) detectError("NEED_KAKAO_TOKEN", 401);
```

2023-02-03 06:15 UTC, sangwoong03 commented on .vscode/launch.json
> +}
해당 파일은 불필요해보입니다! `.gitignore` 파일에 추가하여 github 상에서 공유되지 않도록 해주세요!

2023-02-03 06:15 UTC, sangwoong03 commented on api/services/userService.js
> +  }
카카오에서 받는 정보 중 nickname 혹은 email이 없는 경우도 있을 것입니다.
카카오톡 정보에서 이름을 설정하지 않았거나, 카카오 회원가입 자체를 핸드폰 번호로 진행했을 경우가 이에 해당합니다.

따라서 카카오 API를 통해 회원 정보를 받은 후 회원의 특정 정보에 대해 예외처리를 하기 보다는 회원 정보 자체가 오지 않았을 때의 예외 처리를 해주세요.

2023-02-05 08:59 UTC, kyeongraekim requested changes

2023-02-05 08:59 UTC, kyeongraekim commented on .vscode/launch.json
> +}
이 부분 아직 수정 반영 전이네요!

2023-02-06 07:17 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-06 07:17 UTC, merged