[ADD] orders 기능 구현
wecode-bootcamp-korea/41-2nd-BossBaby-backend pull request #9
Opened 2023-02-07 08:56 UTC by yeyunny

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항

2023-02-07 08:57 UTC, yeyunny commented on api/controllers/orderController.js
> +  const { address, totalprice, productId } = req.body;
req.body, req.params, 혹은 req.userId로 받는 기준을 잘 모르겠습니다..

2023-02-07 09:18 UTC, kyeongraekim requested changes

2023-02-07 09:18 UTC, kyeongraekim commented on api/controllers/orderController.js
> +  const { address, totalprice, productId } = req.body;
예윤님 궁금하신 사항 아래와 같이 답변 달아드립니다. 혹시 더 구체적으로 궁금하신 내용이 생기시면 디엠주세요!

- req.body 는 http method POST 기준 body 안에 담겨져서 들어오는 키-밸류 형태의 데이터 객체입니다.
- req.params는 router 기준 /:userId 와 같이, 엔드포인트에 path parameter로 정의해서 들어오는 데이터 정보입니다.
- req.userId는 auth.js와 같은 인가 과정을 심어놓은 코드를 거칠 때 req.userId = userId 시 새롭게 할당해서 넣어둔 데이터 정보입니다.

2023-02-07 09:18 UTC, kyeongraekim commented on api/controllers/orderController.js
> +  const { address, totalprice, productId } = req.body;
가장 정확하고 이해하기 쉬운정보는 다음의 EXPRESS 공식문서의 req 객체 관련 사용법을 한 번 확인해주세요!!~

2023-02-07 09:18 UTC, kyeongraekim commented on api/models/orderDao.js
> +const OrderStatusId = Object.freeze({
- 해당 데이터의 집합은 객체 지향형 프로그래밍 에서 ENUM 이라는 이름으로 많이 불리우는 단편적인 정보의 집합입니다.
- 따라서 OrderStatusEnum 정도의 워딩으로 해당 내용을 변경해주세요!

2023-02-07 09:18 UTC, kyeongraekim commented on api/models/orderDao.js
> +  } catch {
- catch 구문에 error를 인자로 던져주는 모습이 보여야 할 것 같은데 생략되어 있네요!
- catch (error) { } 와 같이 수정해주세요!~

2023-02-07 09:18 UTC, kyeongraekim commented on api/models/orderDao.js
> +  } catch {
- 주문시 총 가격으로 책정된 금액보다 내가 가진 point가 더 적을 때 구매가 불가능하게끔 유도하는 예외처리가 필요할 것으로 보이네요! 해당 내용을 서비스단에서 비즈니스 로직선에서 처리하면 간편하게 해결할 수 있을 것 같습니다!

2023-02-07 11:21 UTC, yeyunny commented on api/services/orderService.js
> +  const userInfo = await userDao.userInfo(userId);
user가 갖고 있는 point이기 때문에 userDao에 다녀오는 것으로 처리했습니다
이게 맞나요..?
user 관련 정보는 userDao에서 처리하고, 
order 관련 정보는 orderDao에서 처리하는 것이 맞는지 확신이 없습니다..!

2023-02-08 01:30 UTC, kyeongraekim requested changes

2023-02-08 01:30 UTC, kyeongraekim commented on api/services/orderService.js
> +  const userInfo = await userDao.userInfo(userId);
네 Service Layer 에서는 더 아랫단에 있는 Dao Layer에 존재하는 모든 파일에 접근 가능해야 합니다. order 서비스가 user dao의 기능이 필요하면 언제든지 쓰일 수 있게 진행해주시면 됩니다!~

2023-02-08 01:30 UTC, kyeongraekim commented on api/utils/error.js
> +};
에러를 핸들링하는 globalErrorHandler의 존재도, 현재 controller내 예외처리 상황을 보니 필요할 것 같아 보이는데, 혹시 모든 에러현상에 대해 올바르게 클라이언트에게 에러메세지를 전달했을까요?

2023-02-08 04:53 UTC, kyeongraekim approved these changes
LGTM!~ 에러처리는 동규님 코드에 녹아져있군요~

2023-02-08 04:53 UTC, merged